apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-w3rt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-w3rt@sha256:0e953c1991cfd1cb4af8c902ee689dc5afc7f8f342a1cf46615d7c7005d08386
        name: my-nodejs
        resources: {}
status: {}
